name: investing_book
channels:
  - default
dependencies:
  - python=3.7
  - sphinx=2.4.4
  - Cython=0.29.21
  - sympy
  - pip
  - pandas=1.0.4
  - matplotlib=3.2.1
  - sphinxcontrib-bibtex=2.4.1
  - pip:
    - jupyter-book
    # remove mlfinlab, replace with another library
    # - git+https://github.com/FriendlyUser/mlfinlab.git
    - sympy
    - mplfinance
    - yfinance
