name: investing_book
channels:
  - default
dependencies:
  - python=3.9
  - Cython=0.29.21
  - sympy
  - pip
  - pip:
    - jupyter-book
    # remove mlfinlab, replace with another library
    # - git+https://github.com/FriendlyUser/mlfinlab.git
    - sphinx
    - sympy
    - mplfinance
    - matplotlib
    - sphinxcontrib-bibtex
    - yfinance
    - pandas
