name: investing_book
channels:
  - default
dependencies:
  - python=3.7
  - sphinx=2.4.4
  - Cython=0.29.21
  - sympy
  - pip
  - pandas=1.0.4
  - matplotlib=3.2.1
  - pip:
    - jupyter-book
    - mlfinlab==1.0.1
    - sympy
    - mplfinance
    - yfinance
